-- MySQL Script generated by MySQL Workbench
-- Fri Jun 19 12:48:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sklep_internetowy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sklep_internetowy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sklep_internetowy` DEFAULT CHARACTER SET utf8 ;
USE `sklep_internetowy` ;

-- -----------------------------------------------------
-- Table `Użytkownicy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Użytkownicy` ;

CREATE TABLE IF NOT EXISTS `Użytkownicy` (
  `ID_użytkownika` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(30) NULL DEFAULT NULL,
  `hasz_hasła` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_użytkownika`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `Użytkownicy` (`email` ASC) VISIBLE;

CREATE UNIQUE INDEX `ID_użytkownika_UNIQUE` ON `Użytkownicy` (`ID_użytkownika` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role` ;

CREATE TABLE IF NOT EXISTS `Role` (
  `ID_rola` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_rola`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_rola_UNIQUE` ON `Role` (`ID_rola` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Role_użytkownika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role_użytkownika` ;

CREATE TABLE IF NOT EXISTS `Role_użytkownika` (
  `Użytkownicy_ID_użytkownika` INT NOT NULL,
  `role_ID_rola` INT NOT NULL,
  PRIMARY KEY (`Użytkownicy_ID_użytkownika`, `role_ID_rola`),
  CONSTRAINT `fk_Role_użytkownikow_Użytkownicy1`
    FOREIGN KEY (`Użytkownicy_ID_użytkownika`)
    REFERENCES `Użytkownicy` (`ID_użytkownika`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_użytkownikow_role1`
    FOREIGN KEY (`role_ID_rola`)
    REFERENCES `Role` (`ID_rola`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Role_użytkownikow_role1_idx` ON `Role_użytkownika` (`role_ID_rola` ASC) VISIBLE;

CREATE UNIQUE INDEX `Użytkownicy_ID_użytkownika_UNIQUE` ON `Role_użytkownika` (`Użytkownicy_ID_użytkownika` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Obiekt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Obiekt` ;

CREATE TABLE IF NOT EXISTS `Obiekt` (
  `ID_obiektu` INT NOT NULL AUTO_INCREMENT,
  `typ` VARCHAR(50) NULL DEFAULT NULL,
  `nazwa` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_obiektu`))
ENGINE = InnoDB
COMMENT = 'Obiekty w systemie (np. Magazyn, Baza danych)';

CREATE UNIQUE INDEX `ID_obiektu_UNIQUE` ON `Obiekt` (`ID_obiektu` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Uprawnienia_obiektu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Uprawnienia_obiektu` ;

CREATE TABLE IF NOT EXISTS `Uprawnienia_obiektu` (
  `ID_obiekt_uprawnienia` INT NOT NULL AUTO_INCREMENT,
  `Obiekt_ID_obiekt` INT NOT NULL,
  `Obiekt_uprawnienia_nazwa` VARCHAR(255) NOT NULL,
  `Uprawnienia_ID_uprawnienia` INT NOT NULL,
  PRIMARY KEY (`ID_obiekt_uprawnienia`),
  CONSTRAINT `obiekt_fk`
    FOREIGN KEY (`Obiekt_ID_obiekt`)
    REFERENCES `Obiekt` (`ID_obiektu`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_obiekt_uprawnienia_obiekt_idx` ON `Uprawnienia_obiektu` (`Obiekt_ID_obiekt` ASC) VISIBLE;

CREATE UNIQUE INDEX `ID_obiekt_uprawnienia_UNIQUE` ON `Uprawnienia_obiektu` (`ID_obiekt_uprawnienia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bezpośrednie_uprawnienia_użytkownika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bezpośrednie_uprawnienia_użytkownika` ;

CREATE TABLE IF NOT EXISTS `Bezpośrednie_uprawnienia_użytkownika` (
  `Użytkownicy_ID_użytkownika` INT NOT NULL,
  `Obiekt_uprawnienia_ID_obiekt_uprawnienia` INT NOT NULL,
  PRIMARY KEY (`Użytkownicy_ID_użytkownika`),
  CONSTRAINT `fk_Bez_Obiekt_uprawnienia1`
    FOREIGN KEY (`Obiekt_uprawnienia_ID_obiekt_uprawnienia`)
    REFERENCES `Uprawnienia_obiektu` (`ID_obiekt_uprawnienia`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bez_Użytkownicy1`
    FOREIGN KEY (`Użytkownicy_ID_użytkownika`)
    REFERENCES `Użytkownicy` (`ID_użytkownika`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Bezposrednie_Uzytkownik_idx` ON `Bezpośrednie_uprawnienia_użytkownika` (`Użytkownicy_ID_użytkownika` ASC) VISIBLE;

CREATE INDEX `fk_Bez_Obiekt_uprawnienia1` ON `Bezpośrednie_uprawnienia_użytkownika` (`Obiekt_uprawnienia_ID_obiekt_uprawnienia` ASC) VISIBLE;

CREATE UNIQUE INDEX `Użytkownicy_ID_użytkownika_UNIQUE` ON `Bezpośrednie_uprawnienia_użytkownika` (`Użytkownicy_ID_użytkownika` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Uprawnienia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Uprawnienia` ;

CREATE TABLE IF NOT EXISTS `Uprawnienia` (
  `ID_uprawnienia` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(50) NOT NULL,
  `Obiekt_uprawnienia_ID_obiekt_uprawnienia` INT NOT NULL,
  PRIMARY KEY (`ID_uprawnienia`),
  CONSTRAINT `fk_Uprawnienia_Obiekt_uprawnienia1`
    FOREIGN KEY (`Obiekt_uprawnienia_ID_obiekt_uprawnienia`)
    REFERENCES `Uprawnienia_obiektu` (`ID_obiekt_uprawnienia`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'rodzaje uprawnień (np.read, write, delete)';

CREATE INDEX `fk_Uprawnienia_Obiekt_uprawnienia1_idx` ON `Uprawnienia` (`Obiekt_uprawnienia_ID_obiekt_uprawnienia` ASC) VISIBLE;

CREATE UNIQUE INDEX `ID_uprawnienia_UNIQUE` ON `Uprawnienia` (`ID_uprawnienia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Rola_uprawnienia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rola_uprawnienia` ;

CREATE TABLE IF NOT EXISTS `Rola_uprawnienia` (
  `rola_id` INT NOT NULL,
  `Obiekt_uprawnienia_ID_obiekt_uprawnienia` INT NOT NULL,
  PRIMARY KEY (`rola_id`, `Obiekt_uprawnienia_ID_obiekt_uprawnienia`),
  CONSTRAINT `rola_id_fk`
    FOREIGN KEY (`rola_id`)
    REFERENCES `Role` (`ID_rola`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rola_uprawnienia_Obiekt_uprawnienia1`
    FOREIGN KEY (`Obiekt_uprawnienia_ID_obiekt_uprawnienia`)
    REFERENCES `Uprawnienia_obiektu` (`ID_obiekt_uprawnienia`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_rola_uprawnienia_Obiekt_uprawnienia1_idx` ON `Rola_uprawnienia` (`Obiekt_uprawnienia_ID_obiekt_uprawnienia` ASC) VISIBLE;

CREATE UNIQUE INDEX `rola_id_UNIQUE` ON `Rola_uprawnienia` (`rola_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Rola_dziedziczenie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rola_dziedziczenie` ;

CREATE TABLE IF NOT EXISTS `Rola_dziedziczenie` (
  `ID_rodzic_rola` INT NOT NULL,
  `ID_dziecko_rola` INT NOT NULL,
  PRIMARY KEY (`ID_rodzic_rola`, `ID_dziecko_rola`),
  CONSTRAINT `fk_dziedziczenie_rodzic`
    FOREIGN KEY (`ID_rodzic_rola`)
    REFERENCES `Role` (`ID_rola`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dziedziczenie_dziecko`
    FOREIGN KEY (`ID_dziecko_rola`)
    REFERENCES `Role` (`ID_rola`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_dziedziczenie_dziecko_idx` ON `Rola_dziedziczenie` (`ID_dziecko_rola` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Klienci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Klienci` ;

CREATE TABLE IF NOT EXISTS `Klienci` (
  `ID_klienta` INT NOT NULL AUTO_INCREMENT,
  `ID_użytkownika` INT NOT NULL,
  `imie` VARCHAR(50) NOT NULL,
  `nazwisko` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefon` VARCHAR(20) NULL DEFAULT NULL,
  `adres_wysylki` TEXT NOT NULL,
  PRIMARY KEY (`ID_klienta`, `ID_użytkownika`, `nazwisko`),
  CONSTRAINT `fk_Klienci_Użytkownicy1`
    FOREIGN KEY (`ID_użytkownika`)
    REFERENCES `Użytkownicy` (`ID_użytkownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Magazyn D1 - Dane Klientów';

CREATE UNIQUE INDEX ON `Klienci` (`email` ASC) VISIBLE;

CREATE UNIQUE INDEX `ID_klienta_UNIQUE` ON `Klienci` (`ID_klienta` ASC) VISIBLE;

CREATE INDEX `fk_Klienci_Użytkownicy1_idx` ON `Klienci` (`ID_użytkownika` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produkt` ;

CREATE TABLE IF NOT EXISTS `Produkt` (
  `ID_produktu` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(150) NOT NULL,
  `cena_Brutto` DECIMAL(10,2) NOT NULL,
  `stan_dostepny` INT NOT NULL DEFAULT 0,
  `VAT` INT(2) NULL,
  PRIMARY KEY (`ID_produktu`))
ENGINE = InnoDB
COMMENT = 'są tu informacje o tym jaki to produkt jakie ma cechy itp, oraz czy jest dostępny i w jakiej ilości (produkt na stronie)';

CREATE UNIQUE INDEX `ID_towaru_UNIQUE` ON `Produkt` (`ID_produktu` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Zamowienia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Zamowienia` ;

CREATE TABLE IF NOT EXISTS `Zamowienia` (
  `ID_zamowienia` INT NOT NULL AUTO_INCREMENT,
  `Klienci_ID_klienta` INT NOT NULL,
  `Użytkownicy_ID_pracownika` INT NOT NULL,
  `data_zlozenia` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `notatki_klienta` VARCHAR(150) NULL DEFAULT NULL,
  `Status_procesu` VARCHAR(45) NOT NULL,
  `Status_kompletności` VARCHAR(45) NOT NULL,
  `licznik_poprawek` INT(1) NOT NULL DEFAULT 0,
  `Klient_wprowadzil_zmiany` INT(1) NOT NULL DEFAULT 0,
  `data_analizy` DATE NOT NULL,
  `Czy_zatwierdzono` INT(1) NOT NULL,
  PRIMARY KEY (`ID_zamowienia`, `Użytkownicy_ID_pracownika`),
  CONSTRAINT `fk_Zamowienia_Klienci1`
    FOREIGN KEY (`Klienci_ID_klienta`)
    REFERENCES `Klienci` (`ID_klienta`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zamowienia_Użytkownicy1`
    FOREIGN KEY (`Użytkownicy_ID_pracownika`)
    REFERENCES `Użytkownicy` (`ID_użytkownika`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Magazyn D3 - Obsługa licznika poprawek i notatek dla Kamila';

CREATE INDEX `Zamowienia_Klienci1_idx` ON `Zamowienia` (`Klienci_ID_klienta` ASC) INVISIBLE;

CREATE INDEX `Zamowienia_Użytkownicy1_idx` ON `Zamowienia` (`Użytkownicy_ID_pracownika` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `Produkty_w_zamowieniu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produkty_w_zamowieniu` ;

CREATE TABLE IF NOT EXISTS `Produkty_w_zamowieniu` (
  `ID_pozycji` INT NOT NULL AUTO_INCREMENT,
  `ID_zamowienia` INT GENERATED ALWAYS AS () VIRTUAL,
  `Produkt_ID_produktu` INT NOT NULL,
  `ilosc` INT NOT NULL,
  `cena_w_dniu_zakupu` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID_pozycji`, `Produkt_ID_produktu`),
  CONSTRAINT `fk_Produkty_w_zamowieniu_Zamowienia1`
    FOREIGN KEY (`ID_zamowienia`)
    REFERENCES `Zamowienia` (`ID_zamowienia`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produkty_w_zamowieniu_Produkt1`
    FOREIGN KEY (`Produkt_ID_produktu`)
    REFERENCES `Produkt` (`ID_produktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produkty_w_zamowieniu_Zamowienia1_idx` ON `Produkty_w_zamowieniu` (`ID_zamowienia` ASC) VISIBLE;

CREATE UNIQUE INDEX `ID_pozycji_UNIQUE` ON `Produkty_w_zamowieniu` (`ID_pozycji` ASC) VISIBLE;

CREATE INDEX `fk_Produkty_w_zamowieniu_Produkt2_idx` ON `Produkty_w_zamowieniu` (`Produkt_ID_produktu` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Faktury`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faktury` ;

CREATE TABLE IF NOT EXISTS `Faktury` (
  `ID_faktury` INT NOT NULL,
  `Użytkownicy_ID_użytkownika` INT NOT NULL,
  `Numer_faktury` VARCHAR(15) NOT NULL,
  `Zamowienia_ID_zamowienia` INT NOT NULL,
  `Zamowienia_Klienci_ID_klienta` INT NOT NULL,
  `data_wystawienia` DATE NOT NULL,
  `data_sprzedazy` DATE NOT NULL,
  `termin_płatności` DATE NOT NULL,
  `metoda_płatności` INT(1) NOT NULL,
  `status_płatności` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID_faktury`, `Użytkownicy_ID_użytkownika`),
  CONSTRAINT `fk_Faktury_Zamowienia1`
    FOREIGN KEY (`Zamowienia_ID_zamowienia` , `Zamowienia_Klienci_ID_klienta`)
    REFERENCES `Zamowienia` (`ID_zamowienia` , `Klienci_ID_klienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faktury_Użytkownicy1`
    FOREIGN KEY (`Użytkownicy_ID_użytkownika`)
    REFERENCES `Użytkownicy` (`ID_użytkownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Faktury_Zamowienia1_idx` ON `Faktury` (`Zamowienia_ID_zamowienia` ASC, `Zamowienia_Klienci_ID_klienta` ASC) VISIBLE;

CREATE UNIQUE INDEX `Zamowienia_ID_zamowienia_UNIQUE` ON `Faktury` (`Zamowienia_ID_zamowienia` ASC) VISIBLE;

CREATE INDEX `fk_Faktury_Użytkownicy1_idx` ON `Faktury` (`Użytkownicy_ID_użytkownika` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Zwrot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Zwrot` ;

CREATE TABLE IF NOT EXISTS `Zwrot` (
  `ID_Zwrot` INT NOT NULL,
  `ID_zamowienia` INT NOT NULL,
  `powod_zwrotu` VARCHAR(150) NULL,
  `kod_powodu_zwrotu` INT(1) NOT NULL COMMENT 'Produkt uszkodzony/Niezgodność z zamówieniem/Zamówienie niekompletne/Po prostu mi się nie podoba\n',
  PRIMARY KEY (`ID_Zwrot`),
  CONSTRAINT `fk_Wysyłki_Zamowienia1`
    FOREIGN KEY (`ID_zamowienia`)
    REFERENCES `Zamowienia` (`ID_zamowienia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_Zwrot_UNIQUE` ON `Zwrot` (`ID_Zwrot` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Wysyłka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wysyłka` ;

CREATE TABLE IF NOT EXISTS `Wysyłka` (
  `ID_Wysyłki` INT NOT NULL,
  `ID_klienta` INT NOT NULL,
  `ID_użytkownika` INT NOT NULL,
  `ID_zamowienia` INT NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `kod_sposobu_dostawy` INT(1) NOT NULL,
  `data_wyslania` DATE NULL,
  `data_dostarczenia` DATE NULL,
  PRIMARY KEY (`ID_Wysyłki`, `ID_użytkownika`, `ID_zamowienia`),
  CONSTRAINT `fk_Wysyłka_Zamowienia1`
    FOREIGN KEY (`ID_zamowienia`)
    REFERENCES `Zamowienia` (`ID_zamowienia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wysyłka_Użytkownicy1`
    FOREIGN KEY (`ID_użytkownika`)
    REFERENCES `Użytkownicy` (`ID_użytkownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Wysyłka_Zamowienia1_idx` ON `Wysyłka` (`ID_zamowienia` ASC) VISIBLE;

CREATE INDEX `fk_Wysyłka_Użytkownicy1_idx` ON `Wysyłka` (`ID_użytkownika` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Towary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Towary` ;

CREATE TABLE IF NOT EXISTS `Towary` (
  `ID_towaru` INT NOT NULL AUTO_INCREMENT,
  `Produkt_ID_produktu` INT NOT NULL,
  `nazwa` VARCHAR(150) NOT NULL,
  `stan_dostepny` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID_towaru`, `Produkt_ID_produktu`, `nazwa`),
  CONSTRAINT `fk_Towary_Produkt1`
    FOREIGN KEY (`Produkt_ID_produktu`)
    REFERENCES `Produkt` (`ID_produktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Konkretny produkt (fizycznie dla magazyniera, na jakiej półce czy coś xD)\n';

CREATE INDEX `fk_Towary_Produkt1_idx` ON `Towary` (`Produkt_ID_produktu` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Cennik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cennik` ;

CREATE TABLE IF NOT EXISTS `Cennik` (
  `ID_cennika` INT NOT NULL,
  `Produkt_ID_produktu` INT NOT NULL,
  `Towary_nazwa_towaru` VARCHAR(45) NOT NULL,
  `Data_rozpoczęcia` DATE NOT NULL,
  `Data_zakończenia` DATE NULL,
  `Cena_Brutto` DECIMAL(10,2) NOT NULL,
  `VAT` INT(2) NOT NULL,
  PRIMARY KEY (`ID_cennika`, `Produkt_ID_produktu`, `Cena_Brutto`, `VAT`),
  CONSTRAINT `fk_Cenniki_Towary1`
    FOREIGN KEY (`Towary_nazwa_towaru`)
    REFERENCES `Towary` (`nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cennik_Produkt1`
    FOREIGN KEY (`Produkt_ID_produktu`)
    REFERENCES `Produkt` (`ID_produktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cenniki_Towary1_idx` ON `Cennik` (`Towary_nazwa_towaru` ASC) VISIBLE;

CREATE INDEX `fk_Cennik_Produkt1_idx` ON `Cennik` (`Produkt_ID_produktu` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Zarezerwowane_towary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Zarezerwowane_towary` ;

CREATE TABLE IF NOT EXISTS `Zarezerwowane_towary` (
  `ID_rezerwacji` INT NOT NULL,
  `Towary_ID_towaru` INT NOT NULL,
  `Data_rezerwacji` DATE NOT NULL,
  `Data_wysylki` DATE NULL,
  `Cennik_ID_cennika` DECIMAL(10,2) NOT NULL,
  `Cennik_Cena_Brutto` DECIMAL(10,2) NOT NULL,
  `Cennik_VAT` INT(2) NOT NULL,
  PRIMARY KEY (`ID_rezerwacji`),
  CONSTRAINT `fk_Zarezerwowane_towary_Towary1`
    FOREIGN KEY (`Towary_ID_towaru`)
    REFERENCES `Towary` (`ID_towaru`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zarezerwowane_towary_Cennniki1`
    FOREIGN KEY (`Cennik_ID_cennika` , `Cennik_Cena_Brutto` , `Cennik_VAT`)
    REFERENCES `Cennik` (`ID_cennika` , `Cena_Brutto` , `VAT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_towaru_UNIQUE` ON `Zarezerwowane_towary` (`ID_rezerwacji` ASC) VISIBLE;

CREATE INDEX `fk_Zarezerwowane_towary_Towary1_idx` ON `Zarezerwowane_towary` (`Towary_ID_towaru` ASC) VISIBLE;

CREATE INDEX `fk_Zarezerwowane_towary_Cennniki1_idx` ON `Zarezerwowane_towary` (`Cennik_ID_cennika` ASC, `Cennik_Cena_Brutto` ASC, `Cennik_VAT` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Logi_błędów`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Logi_błędów` ;

CREATE TABLE IF NOT EXISTS `Logi_błędów` (
  `ID_Błędu` INT NOT NULL,
  `Nazwa_błędu` VARCHAR(45) NOT NULL,
  `Zamowienia_ID_zamowienia` INT NOT NULL,
  `Data_wystąpienia_błędu` DATE NOT NULL,
  `Notatka_błędu` VARCHAR(200) NULL,
  PRIMARY KEY (`ID_Błędu`),
  CONSTRAINT `fk_Logi_błędów_Zamowienia1`
    FOREIGN KEY (`Zamowienia_ID_zamowienia`)
    REFERENCES `Zamowienia` (`ID_zamowienia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Logi_błędów_Zamowienia1_idx` ON `Logi_błędów` (`Zamowienia_ID_zamowienia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Pozycje_faktur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pozycje_faktur` ;

CREATE TABLE IF NOT EXISTS `Pozycje_faktur` (
  `Faktury_ID_faktury` INT NOT NULL,
  `Faktury_Użytkownicy_ID_użytkownika` INT NOT NULL,
  `ID_produktu` INT NOT NULL,
  `ilość` INT NOT NULL,
  `Cena Netto` DECIMAL(10,2) NOT NULL,
  `Cena_Brutto` DECIMAL(10,2) NOT NULL,
  `stawka_VAT` INT(2) NOT NULL,
  PRIMARY KEY (`Faktury_ID_faktury`, `Faktury_Użytkownicy_ID_użytkownika`, `ID_produktu`),
  CONSTRAINT `fk_Pozycje_faktur_Faktury1`
    FOREIGN KEY (`Faktury_ID_faktury` , `Faktury_Użytkownicy_ID_użytkownika`)
    REFERENCES `Faktury` (`ID_faktury` , `Użytkownicy_ID_użytkownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pozycje_faktur_Cennik1`
    FOREIGN KEY (`ID_produktu` , `Cena_Brutto` , `stawka_VAT`)
    REFERENCES `Cennik` (`Produkt_ID_produktu` , `Cena_Brutto` , `VAT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pozycje_faktur_Cennik1_idx` ON `Pozycje_faktur` (`ID_produktu` ASC, `Cena_Brutto` ASC, `stawka_VAT` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
